### ISSUE TITLE
16 Channels Out of Range Exception

### ISSUE THREAD

**Issue by Mutty99** [reznet/S3MParser#1]
I built the executable with Visual Studio 2022, but when I try to execute the program to convert One Must Fall 2097 Menu's Theme (S3M format), the program gives this exception:
![Immagine 2022-07-15 003630](https://user-images.githubusercontent.com/94219051/179099999-4bd3169b-e8c5-4461-a696-0896dfb296a9.jpg)

Now I'm stuck, and can't convert my tracker file...

**Comment by reznet** [comment]
@Mutty99 if you can make a copy of your S3M available to me I'll try to debug it.

**Comment by Mutty99** [comment]
There you go

Il giorno gio 19 gen 2023 alle ore 02:56 Jeff Evans <
***@***.***> ha scritto:

**Comment by reznet** [comment]
@Mutty99 it looks like you replied via email but and may have attached the file, but GitHub didn't keep it so I'm not able to see it.  I think you'll need to store the file somewhere like dropbox or google drive and then reply with a link to the file.  Or if you remember where you downloaded the file from, you can reply with that link.

**Comment by Mutty99** [comment]
http://www.mirsoft.info/wogm_download.php?data=YToyOntpOjA7czozOiI3NjMiO2k6MTtpOjE2NzQzMjY2NTQ7fQ==
Get the zip from this site

The file is 03-MENU.S3M

Il giorno sab 21 gen 2023 alle ore 19:36 Jeff Evans <
***@***.***> ha scritto:

**Comment by reznet** [comment]
The issue was that your S3M file used 16 samples and there was a bug where the sample number wasn't correctly mapped to a midi channel.  I've fixed it and introduced an option to map pattern channels to midi channels instead of mapping samples to midi channels.  Try running the program both with and without the -`-channels-from-patterns` option to see which one you prefer.  I wasn't able the get the midi file to load correctly in MuseScore 4, but it did load in MuseScore 3.  Some parts don't look exactly like what you hear, but I think it's because the song doubles notes quietly for echo effects and these notes show up in the score as if they're normal notes.  Another example is that the bass part uses different samples for each octave even though the pitch in the S3M file doesn't change.  Let me know what you think and thanks for reporting the issue and being patient for a fix.

**Comment by Mutty99** [comment]
I must be doing something wrong, because I get this error message whenever I load the compiled exe:

Unhandled Exception: System.IO.FileNotFoundException: An error occurred while loading the file or the assembly 'S3M, Version=1.0.0.0, 
Culture=neutral, PublickeyToken=null’ or one of its dependencies. Specified file not found.

**Comment by reznet** [comment]
If you're not running from VS, make sure you copy all files from the `S3MParser\S3mToMidi\bin\Debug` to wherever you're running it from.  Here are the files I see:

```
CommandLine.dll
CommandLine.xml
S3M.dll
S3M.pdb
S3MParser.exe
S3MParser.exe.config
S3MParser.pdb
Sanford.Collections.dll
Sanford.Multimedia.dll
Sanford.Multimedia.Midi.dll
Sanford.Multimedia.Timers.dll
Sanford.Threading.dll
```

The application now requires .NET 4.8, so you may need to download it:  https://dotnet.microsoft.com/en-us/download/dotnet-framework/net48

it doesn't use any .net 4.8 features, but VS 2022 complained that .NET 4.5 is no longer supported so I upgraded to the latest framework.  If you can't use 4.8 and need an earlier version, I can downgrade it.

Other things to try are to perform a clean build in VS.  Go to the build menu and choose Clean Solution.  Then try running it.

Finally, the only way to debug missing dependencies is to use the [fuslogvw](https://learn.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer) tool which is a pain, but we can try that if nothing else works.

**Comment by Mutty99** [comment]
It finally worked, thanks. One last question before I close the issue: what about the midi soundfont? When imported, the midi plays only piano sounds.

**Comment by reznet** [comment]
closing this issue as the original issue, the channel out of range exception, is fixed.  please open a new issue for custom sound support.
